### ISSUE TITLE
pull requests

### ISSUE THREAD

**Issue by jurij** [tobibechtold/ReadmoreElite#7]
nehmt ihr pull requests an? oder ist die "projektarbeit" noch am laufen und ihr wollt keine weitere mitwirkenden devs?

**Comment by sgraewe** [comment]
Also ich pulle die ganze Zeit fleißig :D

Die Projektarbeit war ja nen eigenes Projekt von tobi :)

**Comment by jurij** [comment]
dann mal schauen :)

eine roadmap wäre ganz nett, gibt bestimmt einige auf rm die mitmachen würden

**Comment by tobibechtold** [comment]
Wie schon erwähnt die Projektarbeit ist vorbei seit Anfang des Monats, hab die Woche auch das Ergebnis bekommen. Gab ne 1,8 da ich die Doku etwas vernachlässigt hab :/

Aber wenn du mitmachen möchtest, go4it

**Comment by tobibechtold** [comment]
Da Jira leider Geld kostet hab ich mal ein Taiga Board erstellt. Hoffe ihr seit alle konform mit Scrum und habt da bock drauf. Macht euch einfach nen Account auf taiga.io und schickt mir ne mail oder so. Ich füge euch dann dem Board hinzu. Da können wir dann erstmal alle möglichen Tasks ins Backlog legen und uns in den Sprints Features rauspicken die wir machen wollen. Fände ich cool wenn wir das ganze agil angehen könnten

**Comment by jurij** [comment]
jira ist für open source projekte kostenlos, kannst denen eine anfrage schicken. 
ansonsten kann ich trello empfehlen.

taiga schaue ich mir mal an.

**Comment by tobibechtold** [comment]
Jira wäre natürlich perfekt :) nutzen das auch auf der Arbeit

dann mache ich das mal

**Comment by tobibechtold** [comment]
Antrag ist gestellt. Könnte aber laut denen 10-14 Tage dauern. Wollen wir so lange das Taiga Board oder Trello nutzen?

**Comment by tobibechtold** [comment]
Ok nevermind. Hab direkt ne free trial bekommen :D https://readmoreelite.atlassian.net/

schickt mir eure email adressen, dann füge ich euch hinzu

**Comment by jurij** [comment]
juRiii.r3@gmail.com
